spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:

          naver:
            client-id: ENC(0ryhL75ty9DPzpCm3xR9h0xxOGYBddlHBb3l//6kPHk=)
            client-secret: ENC(yP4oKUUrldyaMwy1xYVNNn5bumB052Zm)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, profile_image
            client-name: Naver
          kakao:
            clientId: ENC(v3HCSehY14ighRx423yYdd0c+9lPu14JXCBJBcMLKDcZWKRPmCyo5xlYrh9lmr4B)
            scope: friends, talk_message, account_email, profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://ec2-15-164-211-17.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/kakao
            client-authentication-method: POST

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    hibernate:
      ddl-auto: update
scheduler:
  cron:
    member: "0 0 18 * * *"
    study: "0 0 19 * * *"

